- src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporter.java
- src/test/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporterTest.java
The OTel community has agreed that having the export pipeline try to manage all the ways in which exporters might need to do retries is a fools-errand.
So, we should just use the retry logic that we've already built.
> Use the TelemetryClient for retry logic

- README.md
This is from Zach Elwood on NR docs team. 
This PR is to add a ‘how to find data’ section so that customers can find the data they send. I’ve included what I think are the applicable data types [spans] but let me know if there are other data types reported by this exporter. If you think this exporter will change to send other types of data in future, keep in mind it will be important to update this repo with link to that data type.
Also changed some title case to sentence case; small thing but we want headings to be sentence case and not title case, so just something to keep in mind when creating new content.
> New 'find and use data' section from docs team

- build.gradle.kts
- src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporter.java
- src/main/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapter.java
- src/test/java/com/newrelic/telemetry/opentelemetry/examples/BasicExample.java
- src/test/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporterTest.java
- src/test/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapterTest.java
0.2.4 is very close to what will be released as "beta" with 0.3.0, so it seems like a good spot to sync up with the changes to the SDK that are required.
> Update to OTel-Java 0.2.4 and NR Telemetry SDK 0.4.0.

- build.gradle.kts
- src/main/java/com/newrelic/telemetry/opentelemetry/export/AttributesSupport.java
- src/main/java/com/newrelic/telemetry/opentelemetry/export/CommonUtils.java
- src/main/java/com/newrelic/telemetry/opentelemetry/export/DeltaDoubleCounter.java
- src/main/java/com/newrelic/telemetry/opentelemetry/export/DeltaLongCounter.java
- src/main/java/com/newrelic/telemetry/opentelemetry/export/MetricPointAdapter.java
- src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporter.java
- src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporter.java
- src/main/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapter.java
- src/main/java/com/newrelic/telemetry/opentelemetry/export/TimeTracker.java
- src/test/java/com/newrelic/telemetry/opentelemetry/examples/BasicExample.java
- src/test/java/com/newrelic/telemetry/opentelemetry/export/DeltaDoubleCounterTest.java
- src/test/java/com/newrelic/telemetry/opentelemetry/export/DeltaLongCounterTest.java
- src/test/java/com/newrelic/telemetry/opentelemetry/export/MetricPointAdapterTest.java
- src/test/java/com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporterTest.java
- src/test/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporterTest.java
- src/test/resources/simplelogger.properties
This adds a Metric Exporter for OpenTelemetry. It currently targets build 0.3.0 of OpenTelemetry Java.
> First pass Metric Exporter implementation.

- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporter.java
- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporter.java
This PR adds secondary user agent strings for span and metric OpenTelemetry exporters.
> Add OpenTelemetry user-agent string to exporters.

- README.md
- opentelemetry-exporters-newrelic/build.gradle.kts
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/examples/BasicExample.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporterTest.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapterTest.java
changes:
* SpanData is now an interface, with a TestSpanData implementation for testing
* Update example code for Metric Instrument refinements
* Rename of the BatchSpanProcessor, and re-introduction of the builder
Note: we'll want to update the auto-instrumentation support when that gets released, probably next week. This will include adding support for auto-configuration of metric export.
> Update to work with OpenTelemetry-Java 0.5.0

- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporter.java
- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapter.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporterTest.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapterTest.java
The span part of implementing #67
> group spans by resources and create batches for each.

- build.gradle.kts
- opentelemetry-exporters-newrelic-auto/build.gradle.kts
- opentelemetry-exporters-newrelic-auto/src/main/java/com/newrelic/telemetry/opentelemetry/export/auto/NewRelicConfiguration.java
- opentelemetry-exporters-newrelic-auto/src/main/java/com/newrelic/telemetry/opentelemetry/export/auto/NewRelicMetricExporterFactory.java
- opentelemetry-exporters-newrelic-auto/src/main/java/com/newrelic/telemetry/opentelemetry/export/auto/NewRelicSpanExporterFactory.java
- opentelemetry-exporters-newrelic-auto/src/test/java/com/newrelic/telemetry/opentelemetry/export/auto/NewRelicMetricExporterFactoryTest.java
- opentelemetry-exporters-newrelic-auto/src/test/java/com/newrelic/telemetry/opentelemetry/export/auto/NewRelicSpanExporterFactoryTest.java
- opentelemetry-exporters-newrelic/build.gradle.kts
- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/AttributesSupport.java
- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/MetricPointAdapter.java
- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporter.java
- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapter.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/examples/BasicExample.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/DeltaDoubleCounterTest.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/DeltaLongCounterTest.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/MetricPointAdapterTest.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporterTest.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporterTest.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapterTest.java
This also includes a bit of cleanup in the creation of the MetricBatchSender, and a tiny bit of gradle cleanup as well.
> Update to support OpenTelemetry Java 0.6.0

- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/MetricPointAdapter.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/MetricPointAdapterTest.java
As of OpenTelemetry Java v0.6.0, the MinMaxSumCount aggregation properly populates the start timestamp, so we don't have to use the TimeTracker for this one.
> Use the start timestamp on the SummaryPoint, rather than using the TimeTracker

- README.md
Badges are created on the actions UI. Each workflow has an option to create one. 
Not sure which of the workflows (release, publish snapshot, or PR build) we would like to see the badge. Or multiple. 
If  we want a badge for the status of Main, I think we would need to setup a github action that is a chron job of building main.
> change to github actions, add actions badge for PR Build.

- README.md
- opentelemetry-exporters-newrelic/build.gradle.kts
- Use version 0.7.0 of the NR telemetry SDK, to fix issue with infinite tracing cell load shifting.
- After merging, it'd be great if we could cut a new release.
> Use version 0.7.0 of NR SDK

- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/AttributesSupport.java
- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporter.java
- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporter.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporterTest.java
Note: This has a possibility of some cardinality issues. I'm aware of this, and we're going to give it a try, nonetheless. This will help link spans to the appropriate metrics, by instance.
> Add the service.instance.id to the metrics as well.

- CHANGELOG.md
- README.md
I don't know if this should be merged before or after cutting the release.
> Update the CHANGELOG and README for 0.8.0

- opentelemetry-exporters-newrelic-auto/build.gradle.kts
- opentelemetry-exporters-newrelic-auto/src/main/java/com/newrelic/telemetry/opentelemetry/export/auto/NewRelicMetricExporterFactory.java
- opentelemetry-exporters-newrelic-auto/src/main/java/com/newrelic/telemetry/opentelemetry/export/auto/NewRelicSpanExporterFactory.java
- opentelemetry-exporters-newrelic-auto/src/main/resources/META-INF/services/io.opentelemetry.javaagent.tooling.exporter.MetricExporterFactory
- opentelemetry-exporters-newrelic-auto/src/main/resources/META-INF/services/io.opentelemetry.javaagent.tooling.exporter.SpanExporterFactory
Stumbled upon this repo and leveraged it _amply_ to be able to figure out how to setup Auto Exporters for OpenTelemetry Java. In doing so, noticed that there are handwritten `META-INF/service` files kicking around in here. Figured I'd like to give back in some small way for being able to build off of the work done herein!
Verified locally both before and after, the structure of the UberJar's `META-INF/services` contains entries necessary for the [`TracerInstaller`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/TracerInstaller.java#L65-L82) to function as expected.
https://soundcloud.com/slowthai/slowthai-james-blake-mount
> Refactor: Leverage AutoService instead of handwritten META-INF files

- opentelemetry-exporters-newrelic-auto/build.gradle.kts
- opentelemetry-exporters-newrelic-auto/src/main/java/com/newrelic/telemetry/opentelemetry/export/auto/NewRelicConfiguration.java
- opentelemetry-exporters-newrelic-auto/src/main/java/com/newrelic/telemetry/opentelemetry/export/auto/NewRelicMetricExporterFactory.java
- opentelemetry-exporters-newrelic-auto/src/main/java/com/newrelic/telemetry/opentelemetry/export/auto/NewRelicSpanExporterFactory.java
- opentelemetry-exporters-newrelic-auto/src/test/java/com/newrelic/telemetry/opentelemetry/export/auto/NewRelicMetricExporterFactoryTest.java
- opentelemetry-exporters-newrelic-auto/src/test/java/com/newrelic/telemetry/opentelemetry/export/auto/NewRelicSpanExporterFactoryTest.java
The interface moved packages, and this change is required to get the exporters working again.
> update to use 0.9.0 spi change from upstream

- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporter.java
closes [https://github.com/newrelic/opentelemetry-exporter-java/issues/116](https://github.com/newrelic/opentelemetry-exporter-java/issues/116)
> Log a message at debug when SpanBatch is empty.

- opentelemetry-exporters-newrelic-auto/src/test/java/com/newrelic/telemetry/opentelemetry/export/auto/AbstractExporterFactoryTest.java
- opentelemetry-exporters-newrelic-auto/src/test/java/com/newrelic/telemetry/opentelemetry/export/auto/NewRelicMetricExporterFactoryTest.java
- opentelemetry-exporters-newrelic-auto/src/test/java/com/newrelic/telemetry/opentelemetry/export/auto/NewRelicSpanExporterFactoryTest.java
- opentelemetry-exporters-newrelic-auto/src/test/java/com/newrelic/telemetry/opentelemetry/export/auto/TestProperties.java
closes [https://github.com/newrelic/opentelemetry-exporter-java/issues/112](https://github.com/newrelic/opentelemetry-exporter-java/issues/112)
> Change mocked Properties object in tests to just be a simple Properties instance.

- CHANGELOG.md
- README.md
- gradle.properties
Housekeeping after publishing 0.10.0 release.
https://github.com/newrelic/opentelemetry-exporter-java/releases/tag/v0.10.0
> Update changelog and bump snapshot version to 0.11.0

- README.md
This property `otel.exporter.newrelic.enable.audit.logging = true` does not enable audit logging in the underlying telemetry SDK.  
Tested and confirmed it does not work with non-bundled exporter + OTel agent and with our bundle. 
This `newrelic.enable.audit.logging = true` enables audit logging.
> remove disabled logging property

- build.gradle.kts
- opentelemetry-exporters-newrelic/build.gradle.kts
When I updated to gradle wrapper 6.7.1, I broke artifact publishing because gradle added additional safety checks which the project's publishing was relying on not being present. The additional safety checks are described briefly here: https://docs.gradle.org/current/userguide/upgrading_version_6.html#publishing_spring_boot_applications
We're not a spring boot app, but were suffering from a similar problem due to our use of the shadow jar plugin in the `opentelemetry-exporters-newrelic-auto` module. I've fixed the problem by explicitly declaring the artifacts that should be published, and take advantage of the fact that `:opentelemetry-exporters-newrelic:jar` and `:opentelemetry-exporters-newrelic-auto:shadowJar` produce artifacts with the same pattern despite being two different task …
> fix artifact publishing with gradle 6.7.1

- CHANGELOG.md
- README.md
- opentelemetry-exporters-newrelic-auto/build.gradle.kts
- opentelemetry-exporters-newrelic-auto/src/test/java/com/newrelic/telemetry/opentelemetry/export/auto/NewRelicMetricExporterFactoryTest.java
- opentelemetry-exporters-newrelic/build.gradle.kts
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/examples/BasicExample.java
Addresses https://github.com/newrelic/opentelemetry-exporter-java/issues/132
Ran with otel Java agent 0.11.0:
```
-javaagent:/path/to/spring-petclinic/opentelemetry/opentelemetry-javaagent-all.jar
-Dotel.exporter.jar=/path/to/opentelemetry-exporter-java/opentelemetry-exporters-newrelic-auto/build/libs/opentelemetry-exporters-newrelic-auto-0.11.0-SNAPSHOT.jar
-Dnewrelic.api.key=<KEY>
-Dnewrelic.service.name=otel-distro-test
-Dio.opentelemetry.javaagent.slf4j.simpleLogger.log.com.newrelic.telemetry=debug
-Dnewrelic.enable.audit.logging=true
```
```
[opentelemetry.auto.trace 2020-12-09 22:25:08:285 -0800] [main] INFO com.newrelic.telemetry.transport.BatchDataSender - BatchDataSender configured with endpoint https://trace-api.newrelic.com/trace/v1
[opentelemetry.auto.trace 2020-12-09 …
```
> Support otel sdk 0.11.0

- CHANGELOG.md
- opentelemetry-exporters-newrelic-auto/build.gradle.kts
- opentelemetry-exporters-newrelic/build.gradle.kts
- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/AttributesSupport.java
- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporter.java
- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapter.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/AttributesSupportTest.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapterTest.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/TestSpanData.java
This adds support to the exporter for OpenTelemetry SDK v0.12.0. There were a few breaking changes to the SDK that had to be addressed in the exporter: https://github.com/open-telemetry/opentelemetry-java/releases/tag/v0.12.0
```
-javaagent:/Users/jkeller/code/spring-petclinic/opentelemetry/opentelemetry-javaagent-0.12.1-all.jar
-Dotel.exporter.jar=/Users/jkeller/code/opentelemetry-exporter-java/opentelemetry-exporters-newrelic-auto/build/libs/opentelemetry-exporters-newrelic-auto-0.12.0-SNAPSHOT.jar
-Dnewrelic.api.key=KEY
-Dnewrelic.service.name=otel-distro-test
-Dio.opentelemetry.javaagent.slf4j.simpleLogger.log.com.newrelic.telemetry=debug
-Dnewrelic.enable.audit.logging=true
```
```
[opentelemetry.auto.trace 2020-12-11 17:30:12:708 -0800] [main] INFO …
```
> Add support for OTel 0.12.0

- CHANGELOG.md
- opentelemetry-exporters-newrelic-auto/build.gradle.kts
- opentelemetry-exporters-newrelic/build.gradle.kts
- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/MetricPointAdapter.java
- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporter.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/MetricPointAdapterTest.java
- opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporterTest.java
Lots of refactoring to be compatible with the OTel SDK 0.13.1 release.
```
- Updates compatibility with `io.opentelemetry:opentelemetry-sdk:0.13.1`
- Updates compatibility with `io.opentelemetry.javaagent:opentelemetry-javaagent-spi:0.13.1`
- Updates compatibility with `com.newrelic.telemetry:telemetry::0.10.0`
- Updates compatibility with `com.newrelic.telemetry:telemetry-http-okhttp::0.10.0`
```
Resolves #145
> Add support for OTel 0.13.1

- build.gradle.kts
- gradle.properties
- opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicExporters.java
Resolves #149 
A previous change to the `build.gradle.kts` (#128) resulted in the project being compiled by Java 11 instead of 8. This PR should fix the issue so that the exporter can run on earlier versions of Java once again.
> Fix publishing to compile with Java 8
