CHANGELOG.md
README.md
build.gradle.kts
gradle.properties
src/main/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapter.java
src/test/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporterTest.java
src/test/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapterTest.java

update to be compliant with 0.2.0-SNAPSHOT of Open Telemetry

---

azure-pipelines.yml
build.gradle.kts

pin the version of otel libraries to 0.2.0

---

README.md
src/test/java/com/newrelic/telemetry/opentelemetry/examples/BasicExample.java

And add an example that gets compiled with every build. Resolves #17

Update the example code in the README

---

README.md
src/main/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapter.java
src/test/java/com/newrelic/telemetry/opentelemetry/examples/BasicExample.java
src/test/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapterTest.java
src/test/resources/simplelogger.properties

Also, make the sample code a bit more canonical, and update the README.

Update the instrumentation.provider to be more general.

---

src/test/java/com/newrelic/telemetry/opentelemetry/examples/BasicExample.java

This makes it actually send spans.

one little tiny fix to the basic example. 

---

README.md
gradle.properties

because we're now targetting 0.3.0 of OTel

rev the release to 0.3.0-SNAPSHOT

---

gradle.properties
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapter.java
opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapterTest.java

Add span.kind to the attributes we send

---

README.md

Fix broken readme link

---

CHANGELOG.md
gradle.properties

And, update the CHANGELOG for 0.4.0

Back to a SNAPSHOT release version

---

opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapter.java
opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapterTest.java

send errors even when description is missing.

---

README.md
opentelemetry-exporters-newrelic-auto/src/main/java/com/newrelic/telemetry/opentelemetry/export/auto/NewRelicSpanExporterFactory.java
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/AttributeNames.java
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/AttributesSupport.java
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporter.java
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapter.java
opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/examples/BasicExample.java
opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/MetricPointAdapterTest.java
opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporterTest.java
opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapterTest.java

Consolidate attribute names

---

opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/AttributesSupportTest.java

Add AttributesSupport tests

---

README.md
azure-pipelines-publish.yml
azure-pipelines.yml

(note the target branch is `main`).
Set up to address #78 
Once this is complete, we can drop master and set main to primary.

prepare for master->main rename

---

opentelemetry-exporters-newrelic/build.gradle.kts
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporter.java
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporter.java
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/VersionFinder.java

include a version file in the exporter and use it at runtime

---

CHANGELOG.md
README.md
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicExporters.java
opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/examples/BasicExample.java
opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/NewRelicExportersTest.java

Add a simpler "one stop shop" for configuring and starting up the New Relic exporters

---

opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/AttributeNames.java
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporter.java
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapter.java
opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/AttributesSupportTest.java
opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapterTest.java

Populate the service.instance.id attribute if it's not on the Resource

---

README.md
opentelemetry-exporters-newrelic-auto/build.gradle.kts
opentelemetry-exporters-newrelic/build.gradle.kts
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/AttributeNames.java
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/AttributesSupport.java
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/MetricPointAdapter.java
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicExporters.java
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporter.java
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapter.java
opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/examples/BasicExample.java
opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/AttributesSupportTest.java
opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/MetricPointAdapterTest.java
opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/NewRelicMetricExporterTest.java
opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/NewRelicSpanExporterTest.java
opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/SpanBatchAdapterTest.java
opentelemetry-exporters-newrelic/src/test/java/com/newrelic/telemetry/opentelemetry/export/TestSpanData.java

This should get us in sync with the latest release of opentelemetry java.
Lots of breaking changes in upstream, so a pretty good number of lines touched.

Update to otel java 0.9.1

---

README.md

fixes [https://github.com/newrelic/opentelemetry-exporter-java/issues/113](https://github.com/newrelic/opentelemetry-exporter-java/issues/113)

Update documentation for system properties

---

opentelemetry-exporters-newrelic-auto/build.gradle.kts
opentelemetry-exporters-newrelic/build.gradle.kts
opentelemetry-exporters-newrelic/src/main/java/com/newrelic/telemetry/opentelemetry/export/AttributesSupport.java

Just 1 small breaking API change from what I can tell.

update to sdk version 0.10.0

---

README.md

I've reorganized and hopefully added some clarity around the usage patterns of the exporter. This was based on my experience getting started with the exporter and using the existing readme.

reorganize readme to improve clarity of usage of patterns

---

gradle.properties

Bump snapshot version

---

CHANGELOG.md
gradle.properties

Update changelog and bump snapshot version.

Post release cleanup
